version: '2'

volumes:
  database_data:
    driver: local

services:
  nginx: 
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./code:/code
    links:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./code:/code
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin